### ISSUE TITLE
Experiment is failing

### ISSUE THREAD

**Issue by himanshuahlawat31** [solliancenet/udacity-intro-to-ml-labs#1]
While running the experiment i am getting error as non compatible  column types
![image](https://user-images.githubusercontent.com/57964598/84588632-c38d9100-ae46-11ea-83e5-7375a4dab274.png)

![image](https://user-images.githubusercontent.com/57964598/84588635-cd16f900-ae46-11ea-8116-c363c8b2db0c.png)

**Comment by shirolkar** [comment]
This should be fixed now.
